services:
  video-streaming-server:
    image: bluenviron/mediamtx:latest
    ports:
      - 8554:8554
  
  alert-service:
    build: .
    command: python alert_service.py --rtsp_url rtsp://video-streaming-server:8554/0
    depends_on:
      - video-streaming-server
    environment:
      - RTSP_URL=rtsp://video-streaming-server:8554/0